### ISSUE TITLE
german language disabled

### ISSUE THREAD

**Issue by Mandraval** [4andreas/Drono#1]
german language disabled

locale = "en";
if Turbine.Engine:GetLanguage() == Turbine.Language.German then
	locale = "de"
--elseif Turbine.Engine:GetLanguage() == Turbine.Language.French then
--	locale = "fr"
--elseif Turbine.Engine:GetLanguage() == Turbine.Language.Russian then
--	locale = "en"
end

**Comment by Dromo** [comment]
i deleted german translation since didnt have all strings translated, and originaly made plugin for friend that was using english. Already got full german translation and will be added soon, hopefully with french will follow too
